### PR TITLE
Remove protocol consolidation to fix warning in valid code

### LINKED ISSUE #251: `clock` produces protocol consolidation compiler warning
Even for the example implementation,
```elixir
  defimpl String.Chars, for: Clock do
    def to_string(%Clock{hour: hour, minute: minute}) do
      "#{format(hour)}:#{format(minute)}"
    end 

    defp format(number) do
      number |> Integer.to_string() |> String.pad_leading(2, "0")
    end 
  end 
```

A warning is produced 
```
warning: the String.Chars protocol has already been consolidated, an implementation for Clock has no effect. If you want to implement protocols after compilation or during tests, check the "Consolidation" section in the Protocol module documentation
  /mnt/exercism-iteration/lib/clock.ex:16: Clock (module)
```

There is no warning when compiling the file locally.

This could be due to `ElixirAnalyzer.ExerciseTest.CommonChecks.CompilerWarnings` somehow re-compiling the code several times and not purging the protocol consolidation.

### PR DESCRIPTION
**Pull request by jiegillet**
Closes #251.

My initial hypothesis (in the issue) was not quite right. [Protocol consolidation](https://hexdocs.pm/elixir/Protocol.html#module-consolidation) is a feature that links protocols to their implementation in order to speed up the protocol dispatch. This can only work when all implementations are known, typically at compile time.

In the case of `clock`, when we compile the file in `ElixirAnalyzer.ExerciseTest.CommonChecks.CompilerWarnings`, an extra implementation is defined and the compiler refuses to include it because the "protocol has already been consolidated" at compile time. 

The docs only show how to turn it off for tests, so I brought my hammer for this fix and I turned off the consolidation altogether. The tradeoff is supposedly a performance cost, but I didn't notice any difference. I'm of course open to other ideas.

### CODE REVIEW

File: test/elixir_analyzer/exercise_test/common_checks/compiler_warnings_test.exs [hunk 1]
```diff
@@ -0,0 +1,9 @@
+defmodule ElixirAnalyzer.ExerciseTest.CommonChecks.CompilerWarningsTest do
+  use ExUnit.Case
+  alias ElixirAnalyzer.ExerciseTest.CommonChecks.CompilerWarnings
+
+  test "Implementing a protocol doesn't trigger a compiler warning" do
+    filepath = "test_data/clock/lib/clock.ex"
+    assert CompilerWarnings.run(filepath, nil) == []
+  end
```
Comment (angelikatyborska) [inline test/elixir_analyzer/exercise_test/common_checks/compiler_warnings_test.exs:8]: How can I get this test to fail? Removing `consolidate_protocols: false,` form `mix.exs` doesn't work.

**Comment by angelikatyborska** [comment]
Initially I was worried about this because I remembered something about protocol consolidation being crucial to one exercise, but thankfully that was in the test runner: https://github.com/exercism/elixir-test-runner/pull/51

File: test/elixir_analyzer/exercise_test/common_checks/compiler_warnings_test.exs (hunk 1 above)
Comment (angelikatyborska) [reply test/elixir_analyzer/exercise_test/common_checks/compiler_warnings_test.exs:8]: Nevermind, I was editing `elixir/mix.exs` 🤦‍♀️

**Review by angelikatyborska — APPROVED** [review]

File: test/elixir_analyzer/exercise_test/common_checks/compiler_warnings_test.exs (hunk 1 above)
Comment (jiegillet) [reply test/elixir_analyzer/exercise_test/common_checks/compiler_warnings_test.exs:8]: Hahaha, yeah, that won't work :)
