### PR TITLE
Closes #398 - Fixed newsletter analysis to allow guard clause

### LINKED ISSUE #398: Newsletter in Elixir track has incorrect automated feedback
In submitting to the Elixir track my solution to the Newsletter exercise, I received the following automated feedback. I don't understand why it marks as `Essential` a code suggestion that my submitted code already has.

Screenshot 2023-10-12 at 08 12 55

### PR DESCRIPTION
**Pull request by octowombat**
Following [discussions](https://github.com/exercism/elixir-analyzer/issues/398) with @jiegillet and an upstream code fix.

### CODE REVIEW

File: lib/elixir_analyzer/test_suite/newsletter.ex [hunk 1]
```diff
@@ -107,6 +139,14 @@ defmodule ElixirAnalyzer.TestSuite.Newsletter do
         end
       end
     end
+
+    form do
+      def open_log(_ignore) when _ignore do
+        _block_includes do
+          File.open!(_ignore, [:write])
```
Comment (jiegillet) [inline lib/elixir_analyzer/test_suite/newsletter.ex:146]: Let's also include all of the variations we had before (with and without `File`, with and without `!`). I know they are not all super likely, but we might as well.

File: test_data/two_fer/imperfect_solution/lib/two_fer.ex [hunk 2]
```diff
@@ -1,5 +1,4 @@
 defmodule TwoFer do
-	@someUnusedModuleAttribute 1
```
[the remark this answers is not in the document]
Comment (octowombat) [reply test_data/two_fer/imperfect_solution/lib/two_fer.ex:2]: I did change it as it caused an unused compiler warning and my setup locally stops in that case!!

I will revert the change and retest. Thanks

File: lib/elixir_analyzer/test_suite/newsletter.ex (hunk 1 above)
Comment (octowombat) [reply lib/elixir_analyzer/test_suite/newsletter.ex:146]: I didn't remove any of the existing variants though.

Comment (jiegillet) [reply lib/elixir_analyzer/test_suite/newsletter.ex:146]: I meant let's duplicate all four existing variants and add the `when _ignore`, not just for `File.open!`.

Right now if someone uses 
```elixir
        import File
        def open_log(path) when is_binary(path) do
          open!(path, [:write])
        end
```
It will trigger a comment.

Comment (octowombat) [reply lib/elixir_analyzer/test_suite/newsletter.ex:146]: Gotcha!

File: test_data/two_fer/imperfect_solution/lib/two_fer.ex (hunk 2 above)
[the remark this answers is not in the document]
Comment (jiegillet) [reply test_data/two_fer/imperfect_solution/lib/two_fer.ex]: Yup, the compiler warning is on purpose, so we can test if we actually detect it :)

**Review by jiegillet — APPROVED** [review]
That's great, thank you so much for your contribution!

**Comment by octowombat** [comment]
My pleasure
