### PR TITLE
Raise when unknown expression used in feature/assert_call

### LINKED ISSUE #63: Warn / Error when directives in `feature` or `assert_call` tests are not supported
Both the `feature` and `assert_call` tests use a DSL to specify their success/error conditions.  When a directive is used that isn't supported, it fails silently (see recent PR comment [here](https://github.com/exercism/elixir-analyzer/pull/61#discussion_r637420056)). 

AC: I want to know when I am using a directive that is unsupported so that I can get better feedback when writing tests.

### PR DESCRIPTION
**Pull request by angelikatyborska**
Closes #63

### CODE REVIEW

File: lib/elixir_analyzer/exercise_test/assert_call.ex [hunk 1]
```diff
@@ -34,6 +34,8 @@ defmodule ElixirAnalyzer.ExerciseTest.AssertCall do
   end
 
   defp parse(description, block, should_call) do
+    :ok = validate_call_block(block, should_call)
```
Comment (neenjaw) [inline lib/elixir_analyzer/exercise_test/assert_call.ex:37]: can we move this call to before lines `29` and `33`? Then we can pass the macro_name as an argument rather than using `should_call` and then coupling the macro_names in a deeper function?

**Review by neenjaw — CHANGES_REQUESTED** [review]
Looks good, I think it should be up one more level though so that a deeper level doesn't need to know what the macro names are

File: lib/elixir_analyzer/exercise_test/assert_call.ex (hunk 1 above)
Comment (angelikatyborska) [reply lib/elixir_analyzer/exercise_test/assert_call.ex]: Good idea: [`95b170a` (#66)](https://github.com/exercism/elixir-analyzer/pull/66/commits/95b170a2b5398fed085b1052875b4cffcc53094b)

**Review by neenjaw — APPROVED** [review]
